# https://docs.hedgedoc.org/setup/docker/
# https://docs.hedgedoc.org/configuration/

services:
  database:
    image: postgres:13.4-alpine
    container_name: hedgedoc-db
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: linuxserver/hedgedoc:latest
    container_name: hedgedoc
    ports:
      - ${HEDGEDOC_PORT}:${HEDGEDOC_PORT}
    environment:
      - CMD_DB_URL=postgres://hedgedoc:${POSTGRES_PASSWORD}@database:5432/hedgedoc
      - CMD_DOMAIN=${HEDGEDOC_DOMAIN}
      - CMD_PORT=${HEDGEDOC_PORT}
      - CMD_PROTOCOL_USESSL=true
    volumes:
      - ./data:/hedgedoc/public/uploads
    depends_on:
      - database
    restart: always
