# https://coder.com/docs/code-server/install#docker

version: "3"

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - 0.0.0.0:28080:8080
      - 0.0.0.0:13001:3001
    volumes:
      - ./data/:/root/
      - <VAR>:/home/coder/project # VAR
    user: ${UID}:${GID}
    environment:
      - DOCKER_USER=$USER
    restart: always
