# https://hub.docker.com/r/jerryin/zerotier-moon


services:
  zerotier-moon:
    image: jerryin/zerotier-moon:latest
    container_name: zerotier-moon
    command: -4 ${ZEROTIER_PUBLIC_IP}
    volumes:
      - ./data:/var/lib/zerotier-one
    network_mode: host
    restart: always
