# https://hub.docker.com/r/jerryin/zerotier-moon
#
version: "3"

services:
  zerotier-moon:
    image: jerryin/zerotier-moon:latest
    container_name: zerotier-moon
    network_mode: host
    volumes:
      - ./data:/var/lib/zerotier-one
    command: -4 <> # Change <> to your public IP
    restart: always
