services:
  asspp:
    image: ghcr.io/lakr233/assppweb:latest
    container_name: asspp
    ports:
      - 18080:18080
    volumes:
      - ./data:/data
    environment:
      - DATA_DIR=/data
      - PORT=18080
      - DOWNLOAD_THREADS=8
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
