# https://github.com/easychen/CookieCloud
version: "3"

services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    container_name: cookiecloud
    ports:
      - 8088:8088
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
