# https://www.v2ray.com/en/welcome/install.html

services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - 8848:8848
    volumes:
      - ./data:/etc/v2ray
    restart: always
