# https://github.com/zyclonite/zerotier-docker
# https://hub.docker.com/r/seedgou/zerotier

services:
  zerotier-one:
    image: zyclonite/zerotier:latest
    container_name: zerotier-one
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./data:/var/lib/zerotier-one
    network_mode: host
    restart: always
