# https://hub.docker.com/r/vocrx/snell-server/tags
# https://github.com/vocrx/Surge/tree/main/snell-server-docker
version: "3"

services:
  snell-server:
    image: vocrx/snell-server:latest
    container_name: snell-server
    environment:
      PORT: ${SNELL_PORT}
      PSK: ${SNELL_PSK}
      IPV6: "${SNELL_IPV6}"
    network_mode: host
    restart: always
