# v3 is for shadowrocket
# https://hub.docker.com/r/cary17/snell/tags

services:
  snell-server:
    image: cary17/snell:v3.0.1
    container_name: snell-server
    environment:
      - PORT=${SNELL_PORT}
      - PSK=${SNELL_PSK}
      - IPV6=${SNELL_IPV6}
    network_mode: host
    restart: always
