# https://hub.docker.com/r/fredliang/derper


services:
  derper:
    image: fredliang/derper:latest
    container_name: derper
    ports:
      - 80:80
      - 443:443
      - 3478:3478
      - 3000:3000
    environment:
      - DERP_DOMAIN=${DERP_DOMAIN}
      - DERP_VERIFY_CLIENTS=false
      - DERP_CERT_DIR=/app/ssl
    volumes:
      - ./data:/app/ssl
    restart: always
