# https://linux.do/t/topic/134001
# https://linux.do/t/topic/136358
# https://github.com/wozulong/fuclaude
# https://hub.docker.com/r/pengzhile/fuclaude

version: "3"

services:
  fuclaude:
    image: pengzhile/fuclaude:latest
    container_name: fuclaude
    ports:
      - "0.0.0.0:${FUCLAUDE_BIND_PORT}:${FUCLAUDE_BIND_PORT}"
    environment:
      - TZ=Asia/Shanghai
      - FUCLAUDE_BIND=0.0.0.0:${FUCLAUDE_BIND_PORT}
      - FUCLAUDE_TIMEOUT=${FUCLAUDE_TIMEOUT}
      - FUCLAUDE_PROXY_URL=${FUCLAUDE_PROXY_URL}
      - FUCLAUDE_REAL_LOGOUT=${FUCLAUDE_REAL_LOGOUT}
      - FUCLAUDE_SITE_PASSWORD=${FUCLAUDE_SITE_PASSWORD}
      - FUCLAUDE_COOKIE_SECRET=${FUCLAUDE_COOKIE_SECRET}
      - FUCLAUDE_OPENAI_BASE_URL=${FUCLAUDE_OPENAI_BASE_URL}
      - FUCLAUDE_OPENAI_API_KEY=${FUCLAUDE_OPENAI_API_KEY}
      - FUCLAUDE_MODERATION_ENABLED=${FUCLAUDE_MODERATION_ENABLED}
      - FUCLAUDE_SIGNUP_ENABLED=${FUCLAUDE_SIGNUP_ENABLED}
      - FUCLAUDE_SHOW_SESSION_KEY=${FUCLAUDE_SHOW_SESSION_KEY}
    restart: always
