# https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/
# https://catcat.blog/docker-install-rustdesk.html
version: "3"

services:
  hbbs: # RustDesk ID/Rendezvous 服务器
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    command: hbbs
    environment:
      - "RELAY=${RELAY_IP}:21117"
      - "ENCRYPTED_ONLY=1"
      - "KEY=${RUSTDESK_KEY}"
    volumes:
      - ./data/hbbs:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: always

  hbbr: # RustDesk 中继服务器
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    command: hbbr
    volumes:
      - ./data/hbbr:/root
    network_mode: host
    restart: always
