# https://tailscale.com/kb/1282/docker#code-examples

services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    environment:
      - TS_STATE_DIR=/var/lib/tailscale # 状态目录, 作用是容器重新启动后配置不变
      - TS_AUTHKEY={TS_AUTHKEY} # 获取方法：TS管理页面 → Settings → Keys → Generate auth key，创建好了复制过来
      - TS_ROUTES=${TS_ROUTES} # 子网路由，推荐使用，设置成自己的网段
      - TS_HOSTNAME=${TS_HOSTNAME} # 节点名字, 可自定义
    volumes:
      - ./data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    privileged: true
    network_mode: host
    restart: always
