# https://www.usememos.com/docs/install/container-install
version: "3"

services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 5230:5230
