# https://github.com/alexta69/metube
services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./data:/downloads
      - ./config:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
