# https://hub.docker.com/r/tsl0922/ttyd


services:
  ttyd:
    image: tsl0922/ttyd:latest
    container_name: ttyd
    hostname: ttyd
    command: ttyd -c ${TTYD_USERNAME}:${TTYD_PASSWORD} -t titleFixed="ttyd" -p ${TTYD_PORT} -W bash
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/host:rw
    network_mode: host
    restart: always
