# https://github.com/MoonTechLab/LunaTV

services:
  moontv-core:
    image: ghcr.io/moontechlab/lunatv:latest
    container_name: moontv-core
    restart: always
    ports:
      - 3000:3000
    environment:
      - USERNAME=REDACTED
      - PASSWORD=${MOONTV_PASSWORD:-admin123}
      - NEXT_PUBLIC_STORAGE_TYPE=upstash
      - UPSTASH_URL=${UPSTASH_URL}
      - UPSTASH_TOKEN=${UPSTASH_TOKEN}
